# Local, CMake-free build of obs-edge-fade.
#
# The Visual Studio generator needs the Windows SDK's MSBuild integration
# component (Microsoft.Cpp.WindowsSDK / ucrt.props), and OBS's own CMake needs
# the Visual Studio generator, so this script builds the plugin directly with
# cl.exe using an import library generated from the installed obs.dll.
#
#   pwsh -NoProfile -File tools/local-build-cl.ps1 [-Configuration RelWithDebInfo]
#
# Produces build_manual/obs-edge-fade.dll and a matching data/ folder.

[CmdletBinding()]
param(
    [ValidateSet('RelWithDebInfo', 'Debug', 'Release')]
    [string] $Configuration = 'RelWithDebInfo',
    [string] $ObsInstall = 'C:\Program Files\obs-studio'
)

$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$deps = Join-Path $root '.deps'
$obsSrc = Join-Path $deps 'obs-studio-32.2.2'
$obsDeps = Join-Path $deps 'obs-deps-2026-07-15-x64'
$outDir = Join-Path $root 'build_manual'
$objDir = Join-Path $outDir 'obj'
$log = Join-Path $root 'build-manual.log'

if (-not (Test-Path $obsSrc)) { throw "OBS sources missing at $obsSrc (run cmake --preset once)" }
if (-not (Test-Path $obsDeps)) { throw "obs-deps missing at $obsDeps" }

New-Item -ItemType Directory -Force -Path $objDir | Out-Null

# Headers that the real libobs CMake configure would generate.
$obsConfig = @'
#pragma once

#define OBS_DATA_PATH "data"
#define OBS_PLUGIN_PATH "obs-plugins/64bit"
#define OBS_PLUGIN_DESTINATION "obs-plugins"

#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
'@
Set-Content -Path (Join-Path $objDir 'obsconfig.h') -Value $obsConfig -Encoding ASCII

$vcvars = 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
$obsDll = Join-Path $ObsInstall 'bin\64bit\obs.dll'

$steps = @(
    "call `"$vcvars`" >nul"
    "cd /d `"$root`""
    # 1. Import library + module definition straight from the shipped obs.dll.
    "dumpbin /exports `"$obsDll`" > `"$objDir\obs-exports.txt`""
    "python tools\make-import-lib.py `"$objDir\obs-exports.txt`" `"$objDir\obs.lib`" `"$objDir\obs.def`""
    "if errorlevel 1 exit /b 1"
)

$cflags = @(
    '/nologo'
    '/c'
    '/TC'
    '/std:c17'
    '/W3'
    '/Zc:__cplusplus'
    '/Zc:preprocessor'
    '/utf-8'
    '/Brepro'
    '/permissive-'
    '/DUNICODE'
    '/D_UNICODE'
    '/D_CRT_SECURE_NO_WARNINGS'
    '/D_CRT_NONSTDC_NO_WARNINGS'
    "/I`"$objDir`""
    "/I`"$root\src`""
    "/I`"$obsSrc\libobs`""
    "/I`"$obsSrc\libobs\graphics`""
    "/I`"$obsSrc\deps`""
    "/I`"$obsDeps\include`""
)

switch ($Configuration) {
    'Debug' { $cflags += @('/Od', '/MDd', '/Zi', '/DDEBUG', '/D_DEBUG') }
    'Release' { $cflags += @('/O2', '/MD', '/GL') }
    default { $cflags += @('/O2', '/MD', '/Zi', '/GL') }
}

$sources = @(
    'src/plugin-main.c'
    'src/common/color-space.c'
    'src/common/shader-loader.c'
    'src/edge-fade/edge-fade-filter.c'
    'src/edge-fade/edge-fade-settings.c'
    'src/edge-fade/edge-fade-properties.c'
)

# plugin-support.c is generated by the CMake build; reproduce it here from the
# same values buildspec.json feeds to CMake, so the reported version matches.
$buildspec = Get-Content (Join-Path $root 'buildspec.json') -Raw | ConvertFrom-Json
$supportIn = Get-Content (Join-Path $root 'src\plugin-support.c.in') -Raw
$support = $supportIn -replace '@CMAKE_PROJECT_NAME@', $buildspec.name `
    -replace '@CMAKE_PROJECT_VERSION@', $buildspec.version
$supportPath = Join-Path $objDir 'plugin-support.c'
Set-Content -Path $supportPath -Value $support -Encoding UTF8
$sources += ($supportPath -replace [regex]::Escape($root + '\'), '' -replace '\\', '/')
Write-Host "plugin version: $($buildspec.version)"

$compile = @("cl $($cflags -join ' ') /Fo`"$objDir\\`" " + (($sources | ForEach-Object { "`"$_`"" }) -join ' '))
$steps += $compile
$steps += 'if errorlevel 1 exit /b 1'

$objs = $sources | ForEach-Object { Join-Path $objDir ((Split-Path $_ -Leaf) -replace '\.c$', '.obj') }
$link = "link /nologo /DLL /OUT:`"$outDir\obs-edge-fade.dll`" /IMPLIB:`"$outDir\obs-edge-fade.lib`" " +
        (($objs | ForEach-Object { "`"$_`"" }) -join ' ') +
        " `"$objDir\obs.lib`" kernel32.lib user32.lib gdi32.lib shell32.lib advapi32.lib ole32.lib oleaut32.lib uuid.lib"
$steps += $link
$steps += 'if errorlevel 1 exit /b 1'
$steps += 'echo MANUAL_BUILD_DONE'

$script = Join-Path $env:TEMP 'oef-manual-build.cmd'
Set-Content -Path $script -Value ($steps -join "`r`n") -Encoding OEM

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = "$env:ComSpec"
$psi.Arguments = "/v:on /c `"$script`""
$psi.RedirectStandardOutput = $true
$psi.RedirectStandardError = $true
$psi.UseShellExecute = $false
$psi.WorkingDirectory = $root

$process = [System.Diagnostics.Process]::Start($psi)
$stdout = $process.StandardOutput.ReadToEnd()
$stderr = $process.StandardError.ReadToEnd()
$process.WaitForExit()

$all = $stdout + $stderr
Set-Content -Path $log -Value $all -Encoding UTF8
Write-Host $all
Write-Host "exit=$($process.ExitCode) log=$log"
exit $process.ExitCode
