# Generates installer/Payload.g.cs: the plugin files the installer embeds.
#
#   pwsh -NoProfile -File tools/make-installer-payload.ps1
#
# The bytes are written as a base64 literal per file. Embedding them as a C#
# source file rather than through csc resources is deliberate: csc's
# /resource:name,path cannot cope with quoted paths, and .NET Framework csc has
# no /embed:, so this is the only route that survives spaces in the build path.
#
# installer/Payload.g.cs is generated, not hand written; tools/build-installer.ps1
# runs this automatically before compiling.

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$payloadRoot = Join-Path $root 'dist\obs-edge-fade'
if (-not (Test-Path $payloadRoot)) {
    throw "payload not found at $payloadRoot; run tools/package-release.ps1 first"
}

# Same order and names as PayloadRelativePaths / PayloadNames in Installer.cs.
$payloadFiles = @(
    @{ Relative = 'bin\64bit\obs-edge-fade.dll'; Name = 'obs-edge-fade.dll' }
    @{ Relative = 'data\effects\edge-fade.effect'; Name = 'edge-fade.effect' }
    @{ Relative = 'data\locale\en-US.ini'; Name = 'en-US.ini' }
    @{ Relative = 'data\locale\es-ES.ini'; Name = 'es-ES.ini' }
)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine('// <auto-generated>')
[void]$builder.AppendLine('//     Generated by tools/make-installer-payload.ps1. Do not edit by hand.')
[void]$builder.AppendLine('//')
[void]$builder.AppendLine('//     Holds the plugin files the installer extracts, base64 encoded because csc')
[void]$builder.AppendLine('//     cannot attach resources from paths that contain spaces.')
[void]$builder.AppendLine('// </auto-generated>')
[void]$builder.AppendLine()
[void]$builder.AppendLine('namespace ObsEdgeFadeSetup')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    internal static class Payload')
[void]$builder.AppendLine('    {')
[void]$builder.AppendLine('        internal static readonly string[] RelativePaths =')
[void]$builder.AppendLine('        {')
foreach ($entry in $payloadFiles) {
    [void]$builder.AppendLine('            @"' + $entry.Relative + '",')
}
[void]$builder.AppendLine('        };')
[void]$builder.AppendLine()
[void]$builder.AppendLine('        internal static readonly string[] Names =')
[void]$builder.AppendLine('        {')
foreach ($entry in $payloadFiles) {
    [void]$builder.AppendLine('            "' + $entry.Name + '",')
}
[void]$builder.AppendLine('        };')
[void]$builder.AppendLine()
[void]$builder.AppendLine('        internal static readonly string[] Base64 =')
[void]$builder.AppendLine('        {')

foreach ($entry in $payloadFiles) {
    $file = Join-Path $payloadRoot $entry.Relative
    if (-not (Test-Path $file)) { throw "missing payload file: $file" }

    $bytes = [System.IO.File]::ReadAllBytes($file)
    $base64 = [System.Convert]::ToBase64String($bytes)

    Write-Host ("  {0} ({1} bytes)" -f $entry.Relative, $bytes.Length)

    # Split into fixed width chunks so the generated file stays readable in a diff.
    $chunkSize = 100
    $chunks = New-Object System.Collections.Generic.List[string]
    for ($offset = 0; $offset -lt $base64.Length; $offset += $chunkSize) {
        $length = [math]::Min($chunkSize, $base64.Length - $offset)
        $chunks.Add('                "' + $base64.Substring($offset, $length) + '"')
    }

    [void]$builder.AppendLine('            // ' + $entry.Relative)
    [void]$builder.AppendLine(($chunks -join " +`r`n") + ',')
}

[void]$builder.AppendLine('        };')
[void]$builder.AppendLine('    }')
[void]$builder.AppendLine('}')

$output = Join-Path $root 'installer\Payload.g.cs'
Set-Content -Path $output -Value $builder.ToString() -Encoding UTF8
Write-Host "payload: $output"
